apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgre
type: Opaque
data:
  POSTGRES_USER: ZWNvbW1lcmNl # base64 for 'ecommerce'
  POSTGRES_PASSWORD: UGcxMjM0 # base64 for 'Pg1234'
  POSTGRES_DB: ZWNvbW1lcmNl # base64 for 'ecommerce'
